### ISSUE TITLE
Works everywhere except this one page

### ISSUE THREAD

**Issue by jpillora** [quoid/userscripts#114]
Firstly, awesome extension! Finally, an improved, modern TamperMonkey :)

I'm finding scripts do not execute on this page
https://www.ing.com.au/securebanking/

But they do on
https://www.ing.com.au/

EDIT: I figured it out, it was being blocked by CSP, and I looked at the source and it looked like there was fallback code however it turned out I needed: `// @inject-into content`. Not sure if this is a bug with fallback or is expected. Feel free to close :+1:

_System Information:_
> macOS version: 11.3 (20E232) Beta
> Userscripts version: 3.0.2
> Safari version: Version 14.1 (16611.1.21.161.3)

**Comment by quoid** [comment]
Thanks for the report @jpillora 

If you could give me some more info so I can determine whether this is a bug or not.

>  figured it out, it was being blocked by CSP, and I looked at the source and it looked like there was fallback code however it turned out I needed: // @inject-into content

Before changing the value to `content` did you try `auto`?

The default value for `@inject-into` is `page` and fallback won't occur unless the value is `auto`. I did a quick test on that page, while using the `// @inject-into auto` and it seemed to work. However, if you were using `auto` and it was not working, I'd like to investigate a little further.

**Comment by jpillora** [comment]
Yep `auto` works for me too. Closed! Was there a particular reason to not use `auto` as the default?

**Comment by quoid** [comment]
Thanks for checking @jpillora 

> Was there a particular reason to not use auto as the default?

I was just asking myself that right now 🤣

I can't seem to remember why `page` was chosen, it might have just been the original value (since `inject-into` was added later) and I didn't think to change it *or* there was a valid reason I can't think of right now.

I think it's a good idea to make `auto` the default value.

**Comment by jpillora** [comment]
Haha fair enough. If you don't want to modify the default for existing scripts, maybe you could change the default for scripts created after `2021-04-23` (not sure if you have a created timestamp for scripts)?

**Comment by quoid** [comment]
I like the idea of changing it to `auto`. I actually had to check the readme because I thought the default value *was* already `auto`.

I made the [issue](https://github.com/quoid/userscripts/issues/115) and it should get pushed in the next update that is currently in beta.

I am hoping to push that update this weekend when I get all the testing feedback.

**Comment by jpillora** [comment]
Sounds good 😁
