### ISSUE TITLE
Any plans on implementing GM.xmlHttpRequest API 

### ISSUE THREAD

**Issue by sumanth-98-dev** [quoid/userscripts#134]
[GM.xmlHttpRequest API](https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/on-user-script-xhr.js) allows requests to cross the same origin policy boundaries. But native xmlHttpRequest doesn't.

**Comment by quoid** [comment]
There are plans to implement the GM_* APIs, but I do not have a time frame for when that will happen.

Also note, some whats going on in [the file you linked](https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/on-user-script-xhr.js) is simply not possibly with this extension due to the Safari api. For example, replacing headers. I am just pointing out that implementing this would likely have to be done in a completely unique way.

**Comment by quoid** [comment]
Noting the mozilla docs because it looks like this isn't supported in iOS: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

**Comment by quoid** [comment]
this should be added in the next build @sumanth-98-dev

**Comment by sumanth-98-dev** [comment]
Wow this is great @quoid

**Comment by quoid** [comment]
merged https://github.com/quoid/userscripts/commit/b8b8a7ff04e8be1d56be0393a5a8369f0a566c8e
