### ISSUE TITLE
Feature request: Allow writing of hostSelectedSaveLocation with macOS defaults

### ISSUE THREAD

**Issue by maelcum** [quoid/userscripts#157]
_System Information:_
> macOS version: macOS 10.15.7
> Userscripts version: 3.3.1
> Safari version: 14.1.2
> Is this issue related to script injection? No.

Hello,

from what I can see, the 'Save Location' for my scripts, that can be set in the Userscripts.app dialog, is stored in the file `$LOGNAME/Library/Group Containers/group.com.userscripts.macos/Library/Preferences/group.com.userscripts.macos.plist` 
as key `hostSelectedSaveLocation` and the path itself in (some binary?) form as data to this key.

To automate an installation of Userscripts.app, I would like to write this key. I found no way to convert an existing path to the binary form that is used by the <data> tag, nor could I use the macOS `defaults write` to write anything to the preferences.

Is there an existing way to do so, that I am not aware of? Or could this be implemented in a future release of Userscripts.app?

Thanks and have a nice day.

**Comment by quoid** [comment]
@maelcum 

> from what I can see, the 'Save Location' for my scripts, that can be set in the Userscripts.app dialog, is stored in the file

That's right. The user has to set the save location from the containing app because there's no way to invoke a document picker that has access to a file system full url from the extension/browser.

> and the path itself in (some binary?) form as data to this key.

That's a url [`bookmarkData`](https://developer.apple.com/documentation/foundation/nsurl/1417795-bookmarkdata). In order to distribute macOS apps through the app store, *which is important*, the macOS application (and it's extension counterpart) must be [sandboxed](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html). And when an app is sandbox, from my understanding and testing, it's not possible to access non-sandboxed file system urls persistently. When the goal is to allow persistent access to directories outside the app sandbox, security scoped bookmarks must be utilized - [read the docs here](https://developer.apple.com/documentation/professional_video_applications/fcpxml_reference/asset/media-rep_element/bookmark/enabling_security-scoped_bookmark_and_url_access).

The containing app has access to full file system urls so it saves those to a shared userdefaults file (the one you've pointed out above). From there, the extension checks that shared file to see if the key/val exists. If it does, it takes that url's bookmark data and re-saves it, security scoped, to it's own, non-shared, userdefaults. 

It's been a while, but I believe in my initial testing, simply passing the url string did not suffice for this "hand off process". Feel free to validate this and please share your results if you do.

> To automate an installation of Userscripts.app

I'm curious the motivation for wanting to automate the installation process. Are you attempting to include the app/extension in some sort of bundle installer?

> I would like to write this key. I found no way to convert an existing path to the binary form that is used by the tag, nor could I use the macOS defaults write to write anything to the preferences.
>
> Is there an existing way to do so, that I am not aware of? Or could this be implemented in a future release of Userscripts.app?

I am not entirely sure what feature you are asking about, but if it's to *"allow a user to write the file system path for the save/read location outside of the app"* - that is not currently planned. If it is to allow the user to dictate a file system url `string` for the read/save location, that is also not planned.

If that *was* something I was planning, I'd focus on figuring out if a `url.absoluteString` can be passed from a containing app to an extension and be made into a persistent security-scope url bookmark.

If you do decide that this is important enough to you and want to contribute, please send me an email (on my profile page) so we can coordinate. I am working on v4 which was re-written with WebExtension api.

**Comment by maelcum** [comment]
Thank you for your fast and comprehensive answer. 

I am not a developer. Not by any definition. I can script my way round in bash and I have fun trying to automate my frequent setting up the os and apps. I hit an obstacle and innocently asked the dev, if there is something I overlooked, or am not aware of. There is nothing else to my question.

> I am not entirely sure what feature you are asking about

This should have been clear from the explanations above. I am sorry it is not. Please accept my apologies. What I meant was: 
To automate setting the 'hostSelectedSaveLocation' preference, I would like to use the default macOS commands for this, like 'defaults write <preference_file_name> <key> <data>', eg.
    defaults write com.userscripts.macos hostSelectedSaveLocation "$HOME/Scripts/userscripts".
/usr/libexec/plistbuddy would be an alternative, though the tool is unwieldy.

Of course it is possible to write to 'com.userscripts.macos' already, but the key 'hostSelectedSaveLocation' is not picked up from this preference file (which is located in the default $HOME/Library/Preferences folder). No surprise. The app wasn't designed to do that. 
It would probably work, if I could write to '$LOGNAME/Library/Group Containers/group.com.userscripts.macos/Library/Preferences/group.com.userscripts.macos.plist', alas, I don't understand how to mangle 'file:///path/to/userscripts' to the bookmarkData format. (Thank you for the link to the documentation.) I had hoped it is just some base64-or-whatever encoding, which I could to myself in bash.

Another possible solution from my laymens pov would be, that the Userscripts.app would check $HOME/Library/Preferences/com.userscripts.macos.plist (in addition to the one in Group Containers) to check for the 'hostSelectedSaveLocation'. It already writes the path to the last folder opened in the dialog, so it is not a new file, nor is it a new preference, just a different location to check for the preference.

> If you do decide that this is important enough to you and want to contribute, please send me an email (on my profile page) so we can coordinate. I am working on v4 which was re-written with WebExtension api.

Thank you, that offer is very nice. But I do not have the know-how to help. I really am just an end-user. Sorry.

Again, thank you for having taken the time to read and answer. And thank you for providing Userscripts in the first place. I find it the superior of the alternatives out there (and reddit agrees, so there is that!).

**Comment by quoid** [comment]
@maelcum 

> Another possible solution from my laymens pov would be, that the Userscripts.app would check $HOME/Library/Preferences/com.userscripts.macos.plist (in addition to the one in Group Containers) to check for the 'hostSelectedSaveLocation'. It already writes the path to the last folder opened in the dialog, so it is not a new file, nor is it a new preference, just a different location to check for the preference.

Thank you for the detailed explanation as to what you're trying to do. I *think* this might be able to be accomplished. If you are ok with waiting a little, let me experiment a bit, because this sounds interesting to me.

I am *not* sure if we can arbitrarily set bookmark data, without user interaction. What I mean is that I am not sure if we can pass any file url to the plist and be able to make a bookmark from it, but let me experiment with that.

If that is possible, then maybe there can be a specific key, something like `userWrittenSaveLocation` in the shared defaults file. If that key exists then:

- the contain app prints that location as the [`saveLocation`](https://github.com/quoid/userscripts/blob/8e3ecd5aa59e22f557ebfea0c0c25ddf1f05fe64/extension/Userscripts/ViewController.swift#L25)
- the extension checks for it, and if so creates a security scoped bookmark from it and [uses it as the user selected save location](https://github.com/quoid/userscripts/blob/8e3ecd5aa59e22f557ebfea0c0c25ddf1f05fe64/extension/Userscripts%20Extension/Functions.swift#L93)

I can't promise I will get to this quickly but I'd hope to experiment this week with it and report back

**Comment by quoid** [comment]
I don't think I will be able to get to this, so I am closing the issue.
