### ISSUE TITLE
Userscripts extension fails to initialize

### ISSUE THREAD

**Issue by dreed47** [quoid/userscripts#174]
_System Information:_
> macOS version: 12.0.1
> Userscripts version: 3.3.1
> Safari version: 15.1
> Is this issue related to script injection? no
> Did the test script (pasted above) successfully run on your machine? no, extension won't load at all

The extension fails to initialize.  Gives message: Failed to initialize app, check the console!  The console shows the following.

```
Failed to get settings 
index.html:23246 
```

Console also shows:

```
[Error] failed to get settings
	(anonymous function) (index.html:1:884246)
	some
	(anonymous function) (index.html:1:884192)
	J (index.html:1:549675)
	Z (index.html:1:549441)
	promiseReactionJob
```

**Comment by quoid** [comment]
@dreed47 can you please refer to this issue and see if it resolves: https://github.com/quoid/userscripts/issues/160

**Comment by dreed47** [comment]
yes, it seems to be related or the same issue.  I re-installed and specified a local location for the saved file (not in iCloud) and now the app initializes but when I try to save a CSS script I get `failed to parse argument in save function`

**Comment by dreed47** [comment]
I think I had an issue in a specific script.  Seems to be working now, once I moved the save file location to my local disk.

thx

**Comment by quoid** [comment]
@dreed47 you should be able to use your icloud folder as a save location

`failed to parse argument in save function` usually means there is some bad script metadata as you allude to in your last comment - [see ref](https://github.com/quoid/userscripts/blob/aa8c4b0d45ca806e539e7be6805a1b945dc7a422/extension/Userscripts%20Extension/Functions.swift#L848)

**Comment by pnewell** [comment]
I am having the same issue. I am a first time user so my scripts folder is empty. I tried both icloud and localdisk locations and the extension never initializes, it just always says Initializing app... Nothing in the console I can see.

**Comment by quoid** [comment]
@pnewell can you walk me through what is going on and provide system specs and along with what version of the extension you are using?

**Comment by pnewell** [comment]
I installed the app from the App Store, opened it, changed the folder location for scripts to my local disk. Opened Safari, enabled the extension. Click on the extension in the toolbar and hit "Open".

A new tab opens with that says:

Userscripts Safari
Initializing app...

And then it stays there and never changes. I checked the console and no error messages show.

I am on an M1 Macbook Air, Mac OS 12.0, Safari 15.1, Userscripts 3.3.1

**Comment by quoid** [comment]
@pnewell 

This is very strange... The original issue reported in this issue seems different from yours.

The console is *not* giving you an error? Can you provide a screenshot anyway?

I just went through a fresh install process on a machine here that had not had the extension ever installed. It's on macOS 12.0.1 and Safari 15.1, but it is a M1Pro. It installed and ran as expected.

Here are steps you can try to resolve this, if you are willing to give them a try:

**Close safari and the userscripts app if open**

**Remove the app completely**
- delete/uninstall the app
- delete the following folders:
  - `YOURUSERNAME/Library/Containers/Userscripts` (there might be two of them, delete both)
  - `YOURUSERNAME/Library/Group Containers/group.com.userscripts.macos/`
  - `YOURUSERNAME/Library/Group Containers/J74Q8V8V8N.com.userscripts.macos` (if present)

**Re-install App**
When you reinstall the app this time, do *not* change the default save location, just open the app, then activate it in Safari.


From there see if the extension page will load.

If you get the same issue, you can open the Console.app and then see if any messages for Userscripts show:


<img width="825" alt="Screen Shot 2021-12-02 at 5 25 32 PM" src="https://user-images.githubusercontent.com/7660254/144513120-a3b84af9-39cc-47d2-9bdc-edcb4b2f7d24.png">


Further, if you still have issues, I can send you a beta invite to version 4+ and see if that works better for you, but Testflight is required.

**Comment by quoid** [comment]
closed due to inactivity
