### ISSUE TITLE
Need help with a userscript

### ISSUE THREAD

**Issue by specter78** [quoid/userscripts#178]
```
// ==UserScript==
// @name       Redirect
// @match      *://www.reddit.com/*
// @run-at     document-start
// @noframes
// ==/UserScript==

query = window.location.href.split("www.reddit.com")[1];
window.location.href = "https://libredd.it" + query;
```

I want the redirect to happen before page load. However, in reality, redirect happens after the page is loaded.

_System Information:_
> macOS version: 12.0.1
> Userscripts version: 3.3.1
> Safari version: 15.1
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes and No

**Comment by quoid** [comment]
@specter78 

> I want the redirect to happen before page load. 

That's not possible. Injection happens on page load and the soonest you can initiate the redirect is `document-start` as you are already doing. The available options are:

- `@run-at`
    - allows the user to choose the injection timing
    - document-start, document-end (default), document-idle
    - works like [violentmonkey](https://violentmonkey.github.io/api/metadata-block/#run-at)

**Comment by specter78** [comment]
> Can you elaborate on what did not work with the test script?

It is working, but not how I want it to (which you’ve already explained).

**Comment by quoid** [comment]
@specter78 

Currently userscripts execute as soon as possible with document-start. I spent a lot of time trying to get them to execute quicker but it wasn't seemingly possible due to the way webNavigation was handled by Safari web extensions. 

I was hoping to execute the moment a user commits a navigation and inject the user scripts outside of the content script, but alas that was not feasible. 

I'm sorry script execution doesn't match your expectations. In some time I will do some more testing to see if anything changed but for now there's no way around it. 

I wish I could have been of more help.

**Comment by quoid** [comment]
@specter78 I am closing this issue

If you care to track progress, if any, on injection time speed you can do so in this issue #184
