### ISSUE TITLE
Possibly injects too late for some scripts to run successfully?

### ISSUE THREAD

**Issue by fortinmike** [quoid/userscripts#183]
It seems like things might be injected too late for some userscripts to work properly.

For example, [Simple YouTube Age Restriction Bypass](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass) fails to run due to the script running after YouTube defines some "non-configurable properties" which are then locked for modification.

A collaborator hints that it's probably not working because it runs too late:
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/102

What is your take on this? Could injecting scripts be done earlier in the page's lifetime to make userscripts such as this one work? Can something be done within the script itself? I'm guessing this is not the only userscript that's affected by this, if this is indeed something specific to Userscripts (the app).

Thanks!

_System Information:_
> macOS version: 12.1 (21C52)
> Userscripts version: 3.3.1
> Safari version: 15.2 (17612.3.6.1.6)
> Is this issue related to script injection? YES
> Did the test script (pasted above) successfully run on your machine? YES

**Comment by quoid** [comment]
@fortinmike 

As you mentioned in the issue you created in the other repo, I am getting a bunch of errors for that userscript with **multiple** userscript managers for Safari - including this one. I wanted to verify whether or not the issue was specific to this extension and that does not seem to be the case.

That being said, currently injection occurs at the earliest viable time, that I am aware of. It would be ideal if I could have userscripts execute from the background page but because of certain ways Safari handles certain events with WebExtensions, it doesn't seem as viable as it is in Firefox or Chrome. Improving this is an ongoing thing I have been testing for a while. If an quicker alternative to the injection method is found it will certainly be adopted.

That being said, I am not totally sure what is going on with that userscript you linked. Obviously the author would be better suited to debug it and see if he knows of a work around for when injection doesn't happen immediately.

**Comment by fortinmike** [comment]
> Improving this is an ongoing thing I have been testing for a while. If an quicker alternative to the injection method is found it will certainly be adopted.

Great to know! If I have any more relevant info I'll make sure to add it here.

**Comment by quoid** [comment]
@fortinmike 

Do you have an example youtube url for testing the script you linked?

**Comment by fortinmike** [comment]
Here's one: https://www.youtube.com/watch?v=SjDMwsbaSd8

**Comment by quoid** [comment]
@fortinmike I am closing this issue

I opened a new issue talking a bit about why injection is done the way it is done, currently. You can view that here if you are interested: #184 

That will track any progress that is made on the topic
