### ISSUE TITLE
UI is not properly scaled in Split View on iPadOS

### ISSUE THREAD

**Issue by Taxyovio** [quoid/userscripts#186]
![B75FB0B7-F199-4AC2-A607-4BEC1F9ACDC2](https://user-images.githubusercontent.com/38234151/146660692-7d911d9d-d507-4659-a011-899e9073ee15.png)

The UI is not properly scaled to fill the window when splitting Safari in split view in 2/3 width in portrait orientation. Screenshot taken on ipad pro 12.9 running ipados 15.2.

**Comment by quoid** [comment]
@Taxyovio thanks for reporting this, I just verified it.

**Comment by Taxyovio** [comment]
This hasn’t been fixed my end in the beta build 10.

**Comment by quoid** [comment]
@Taxyovio Still broken on mine too. I noticed a typo in the code and didn't thoroughly test it so it went unnoticed

**Comment by Taxyovio** [comment]
Fixed

**Comment by quoid** [comment]
@Taxyovio 

Note: there are still some imperfections when you go from split view, back to a view where the popup is showing as "dropdown" while keeping the popup open. As far as I could tell, this is because even though the styles get updated, the popup doesn't respect those style changes. That seems like an upstream Apple issue which I am going to report. Closing and reopening the popup resolves this, but I wanted to make a note here in case future reports come in, this issue can be referenced.
