### ISSUE TITLE
What is `unsafeWindow` equivalent in UserScripts?

### ISSUE THREAD

**Issue by YaxinCheng** [quoid/userscripts#209]
I have installed a script from greasyfork, which works in tampermonkey on Firefox but not UserScripts on Safari. Here is the error message I get: `ReferenceError: Can't find variable: unsafeWindow`. I am not sure this is because either `unsafeWindow` is not supported by Safari or UsersScripts? 

Here I have a simplified version of that script. 

```
// ==UserScript==
// @name         Test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @author       You
// @match        *://*.google.ca/*
// @grant        unsafeWindow
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    window.alert(unsafeWindow.locals.get('uk'))
})();
```

_System Information:_
> macOS or iOS version: macOS 12.1 (21C52)
> Userscripts version: 4.0.10(42)
> Safari version: 15.2 (17612.3.6.1.6)
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Worked for TamperMonkey on Firefox

**Comment by quoid** [comment]
Thanks for reporting this @YaxinCheng, you're correct, `unsafeWindow` isn't part of [Userscripts API](https://github.com/quoid/userscripts#api) currently.

If you use `@inject-into page`, you should gain access to functions and variables in the window scope. Make sure you choose the right `@run-at` value so that the Userscripts executes at a time where those functions and variables are available. Here's the [metadata references](https://github.com/quoid/userscripts#metadata).

Assuming `locals` is an object at the window level, you should be able to access it as `window.locals`, rather than `unsafeWindow.locals`.

Let me know how that works out.

**Comment by YaxinCheng** [comment]
@quoid Thanks for the quick response! It works when using `@inject-into page`. Now the error turns into: `ReferenceError: Can't find variable: GM_getValue`. But I see you have already created an [issue](https://github.com/quoid/userscripts/issues/189), so I will just wait. 

This problem is solved, so I will close this issue now. Thanks again!
