### ISSUE TITLE
It seems that `// @run-at context-menu` has been broken in the recent beta version

### ISSUE THREAD

**Issue by jaredyam** [quoid/userscripts#256]
_System Information:_
> macOS or iOS version: 12.3.1 (21E258)
> Userscripts version: 4.2.0 (51)
> Safari version: 15.4 (17613.1.17.1.13)
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes

For now I'm using the latest beta version from TestFlight, this issue can not be reproduced in the latest release version 4.1.0 (47).

**Comment by quoid** [comment]
@jaredyam 

In the recent updates it was removed because there are some issues with the pre 4.2 implementation that needs time to rework. I am not sure if I will re-implement before the official 4.2 release.

I am going to track it on this issue: https://github.com/quoid/userscripts/issues/159 

Since it was undocumented/hidden, I silently removed it, but I will call it out in the update notes.

**Comment by jaredyam** [comment]
Sorry for ignoring the issue you mentioned above...

I've came back to use the latest official release which is useful enough in my case. Still looking forward improvements in the coming updates, really appreciate for your amazing work.

**Comment by quoid** [comment]
@jaredyam i should have put it in the update notes so users would have know

**Comment by quoid** [comment]
@jaredyam newest macos build (54) has the updated `@run-at context-menu` functionality - from the user perspective not much changed, but how those menu items get created has changed and should be much more reliable.

Note: `context-menu` scripts now only support `@match` and not `@include` - `@exclude-match` and `@exclude` also have no effect.

The newest update should be on the Testflight soon
