### ISSUE TITLE
AdGuard Popup Blocker 

### ISSUE THREAD

**Issue by michael1900** [quoid/userscripts#257]
_System Information:_
> macOS or iOS version: iOS 15.5
> Userscripts version: 1.1
> Safari version: i don’ know
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? No

Hi. Using this popup blocker from AdGuard: 

https://github.com/AdguardTeam/PopupBlocker

Site tried: 
https://livefootball24.com/match/nejmeh-sc-east-riffa/1512581

If you choose a TV match, for example, and click on the play button to start the streaming then a popup opens a new safari tab. This happens many times before you can watch the match.

I tested it on this site adviced from AdGuard PopupBlocker github page:
http://code.ptcong.com/better-js-popunder-script/

Please help. Test it and let me know if you can. Thank you

**Comment by quoid** [comment]
<img width="1455" alt="Screen Shot 2022-05-18 at 8 57 12 AM" src="https://user-images.githubusercontent.com/7660254/169043932-56332cc8-0a3f-449b-b58d-1200541c0070.png">


The probably is likely due to not supporting all the GM apis being used by the script:

https://github.com/quoid/userscripts/issues/224

Hopefully soon those will be supported.

**Comment by michael1900** [comment]
I have problem also with this site when i try a stream: https://streamgoto.me/a/
Seems to be the same problem i think.

**Comment by quoid** [comment]
@michael1900 

> We will have support in the next update?

Not the next update, but hopefully a future update. If you or anyone else wants to make a code contribution to add these features, that would help.

To keep the conversation focused, I am going to close this issue in favor or #224 since they are related. Feel free to add an context to that issue if needed.

**Comment by michael1900** [comment]
> @michael1900
> 
> > We will have support in the next update?
> 
> Not the next update, but hopefully a future update. If you or anyone else wants to make a code contribution to add these features, that would help.

**Comment by quoid** [comment]
> So sad about this :( Do you know an other extension that supports that PopupBlocker script?

Don't be sad, it will likely get added in a future update. If you need to sooner, like I said, you could code the feature and make a PR and assuming the code is acceptable, I can push it into an update.

**Comment by michael1900** [comment]
Hi. I solved used Macaque extensions. Hope to use Userscripts soon btw.

**Comment by michael1900** [comment]
Any news about supporting all gm api?

**Comment by quoid** [comment]
> Any news about supporting all gm api?

You can check on the status of it within [the issue that was linked](https://github.com/quoid/userscripts/issues/224) and within the [project board](https://github.com/quoid/userscripts/projects). This is not something that will happen quickly, especially not in 11 days.

If you need features faster, please contribute to this project by coding the features and making a pull request.
