### ISSUE TITLE
URL verify logic doesn't support URLs with query string 

### ISSUE THREAD

**Issue by raananzvi** [quoid/userscripts#274]
You can see here a very simplified validation logic which is not robust enough.
If I have an update URL with query string (https://domain/folder/file.js?query=query) this URL will not pass the validation.
You need to extract the URL without the query string (or hash #)
https://github.com/quoid/userscripts/blob/2a83cf0b62932077d0019df5f704c35725f0fa4a/extension/Userscripts%20Extension/Functions.swift#L139

**Comment by quoid** [comment]
Thanks for reporting this @raananzvi 

This can be fixed by using the [the getUrlProps](https://github.com/quoid/userscripts/blob/2a83cf0b62932077d0019df5f704c35725f0fa4a/extension/Userscripts%20Extension/Functions.swift#L1049) function and checking the `protocol` and `pathname` rather than relying on the rudimentary `hasPrefix` and `hasSuffix` checks.

Feel free to make a PR or I will next patch.

**Comment by raananzvi** [comment]
I’m afraid I can’t contribute to open source without some clearance. So I prefer you to fix this.

**Comment by quoid** [comment]
All good, I will get to this
