### ISSUE TITLE
Sync Userscripts

### ISSUE THREAD

**Issue by patrickrushton** [quoid/userscripts#32]
Is there a way to synchronise Userscripts between computers? I tried a few things with aliases and symlinks but didn't succeed.

**Comment by quoid** [comment]
@patrickrushton 

Not at the current time. Aliases won't work because of the way [it's looking for the saved code](https://github.com/quoid/userscripts/blob/bbb00f7b8c0c22bfec7371305a03fd86058c5e03/Userscripts%20Extension/SafariExtensionViewController.swift#L146).

This is certainly a feature that should be added in the future, in some fashion (whether it's supporting aliases or allowing the user to select their "script folder").

**Comment by ticky** [comment]
It’d be great to be able to iCloud sync these like [Cascadea](https://cascadea.app) does for Userstyles! 👍🏼

**Comment by quoid** [comment]
@ticky I agree that would be a good thing

before that I am focused on pushing an update to allow user selected save locations, which will give some ability to sync between machines - after that is out, I will see how much need there is for icloud syncing

**Comment by MisterMediocre** [comment]
The primary reason I even use safari is for sync across multiple mac devices. Would be lovely if this could sync scripts via icloud too.

**Comment by quoid** [comment]
Version 2.1.0 is released. You can now select where you'd like to store your files, which can be an icloud or anything other "syncable" location. It was a huge pain to implement this. 😓
