### ISSUE TITLE
Save the script file as `@name.user.js` instead of `@name.js`

### ISSUE THREAD

**Issue by ACTCD** [quoid/userscripts#320]
Considering that a `user script` is a `javascript` in a specific format and purpose, most script managers and script marketplaces  also use this specific suffix `.user.js` as a way of identification. Whether it should be carried over and persisted to the filesystem.

For my case, I was bothered that every time I edited and saved a script in the `Userscripts` interface, it always changed my original `.user.js` to `.js`, and produce some files in the trash, which caused a certain inconvenience, causing I don't use the built-in editor anymore, I'm used to using an external editor for editing, which works fine due to the way `Userscripts` loads scripts.

So much so that I gradually ignored the problem until I accidentally used the built-in editor again, and this time I recorded it. I would like to hear more opinions, have you encountered the same problem as a script developer?

**Comment by quoid** [comment]
I am not opposed to adding the suffix, `.user.js` to all new userscripts saved through the built in editor. In fact, I think is probably good to implement.

Currently, when a userscript is saved through the built in editor, that filename structure is strictly enforced. For example:

- create a new userscript called `foo.bar.js` in an external editor, with `@name foo`
- put `foo.bar.js` in your scripts folder
- load `foo.bar.js` into the built in editor
  - it will be shown as `foo` in the sidebar because `@name` has a value of `foo`
- make an edit to `foo.bar.js`
- save file
- in the script folder, `foo.bar.js` is trashed and a new file named `foo.js` is saved. 

I wonder if the **current** `filename` should always be respected, regardless of what the value of `@name` is. It seems most other managers make the assumption that `filename` will *always* be `@name.user.js`.
