### ISSUE TITLE
Strict Mode wrapper prevents `@require` libs from working

### ISSUE THREAD

**Issue by LeoNatan** [quoid/userscripts#362]
Hello,

Some change, be it an OS update or a Userscripts update, has broken one of my scripts, on macOS and iOS. I have been on iOS 16 betas for a while, and I think the script worked in that period, and only recently stopped working, so I suspect it’s a change in Userscripts.

The exception thrown:
```
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.
```

<img width="1483" alt="Screenshot 2022-10-28 at 11 43 57" src="https://user-images.githubusercontent.com/2270433/198544899-ac059fb4-dc77-4863-9f77-d689d8cddbf3.png">

The script:
https://raw.githubusercontent.com/LeoNatan/NFOHump/master/EmbedVideos/NFOHumpEmbedVideos.user.js

Can be tested on:
https://www.nfohump.com/forum/viewtopic.php?t=114985

_System Information:_
> macOS or iOS version: 13.1 Beta, 16.2 Beta
> Userscripts version: 4.3.1 (62)
> Safari version: Version 16.1 (18614.3.2.11.2)
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes

**Comment by quoid** [comment]
This error seems to be caused by one of your `@require` resources, I think the reddit one. All code, including `@require` resources are wrapped in an anonymous function [using `strict` mode](https://github.com/quoid/userscripts/blob/d319eab50f53e5ceffcac08f9e6502249437ae61/extension/Userscripts%20Extension/Resources/content.js#L241) which seems to [be the cause of the issue](https://stackoverflow.com/questions/31921189/caller-and-arguments-are-restricted-function-properties-and-cannot-be-access). I've confirmed that disabling strict mode enables your userscript to function as expected (ie. gifs load in that forum post).

The dilemma here is that when using a `@require` library, the userscript author has little/no control over how it is programmed. This means they can not update the code to abide by `strict` mode guidelines.

I am going to update the title of this issue to better reflect the issue.

**Comment by LeoNatan** [comment]
Is this a new change? Until recently, this script used to work as expected.

**Comment by quoid** [comment]
Yes it changed the last update. I'm hoping we can push a hotfix for this in short order, later today if poss.

**Comment by LeoNatan** [comment]
Also worth mentioning that the script functions as expected under Tampermonkey on Firefox. 

Perhaps an option can be given somehow, allowing script developers to opt-in to strict mode? Or opt-out.

**Comment by quoid** [comment]
That's where I am leaning. Users can opt-in if they so choose.

**Comment by LeoNatan** [comment]
Perfect, thank you for your quick response!

**Comment by masklinn** [comment]
FWIW I'm having a similar issue on an extension which apparently does something wonky:

>     SyntaxError: Cannot destructure to a parameter name 'arguments' in strict mode.

Although I'm not entirely sure what it's talking about: the extension doesn't seem to use `arguments` anywhere in its source code. And it's difficult to debug because the traceback goes no further than content.js:278.

**Comment by quoid** [comment]
@masklinn if you are on macOS, could you update to `4.3.2` and see if the issue persists?

The iOS version is still pending review, but the macOS version `4.3.2` has the changes mentioned in this issue.

**Comment by LeoNatan** [comment]
I'll test on Mac later today. Thanks!

**Comment by LeoNatan** [comment]
Can confirm my script works with the latest version. Thanks

**Comment by masklinn** [comment]
@quoid I am on a mac and can also confirm that after update the problematic script has been restored to full functionality, thank you very much.

**Comment by masklinn** [comment]
> It's from some of your user scripts installed, you should be able to see in the console log which script is trying to injecting.

I know what script it was complaining about (the one which stopped working), and i posted the exact error message above:

>     SyntaxError: Cannot destructure to a parameter name 'arguments' in strict mode.

However the script *does not contain `arguments` anywhere*. Which is why I was quite confused (otherwise I could just have fixed the script directly).

**Comment by masklinn** [comment]
> `the exact error message` is not enough for us to provide you with more helpful information, please understand. 

I understand that, I just noted the information I did have have.

> You can also check if it comes from your `@require` dependencies.

Yep :+1:, that's the ticket, one of the `@require`-d script uses `arguments` a parameter to one of its functions. This triggers the error I could observe when put in a strict context:
```js
> (function () {
    "use strict";
    function f(arguments) {}
})()
```
=> `SyntaxError: Cannot destructure to a parameter name 'arguments' in strict mode.`

**Comment by LeoNatan** [comment]
In Safari, you can add an exception breakpoint, and see where exactly this gets thrown.

**Comment by masklinn** [comment]
> In Safari, you can add an exception breakpoint, and see where exactly this gets thrown.

The problem is that because it's a syntax error it's thrown by the loader, it's not thrown by the broken code. I have the entire traceback, but it stops at the extension boundary.
