### ISSUE TITLE
Firing script on page load completion 

### ISSUE THREAD

**Issue by mrstaggs** [quoid/userscripts#38]
I'm trying to get my script to run once all elements are loaded (including external .js scripts). I've tried event listeners and window.onload. Is there any inherent issue with asking this type of script to work inside of the extension?

**Comment by quoid** [comment]
@mrstaggs 

Can you elaborate on your approach to this? What website are you trying your script on and how are you trying to execute your JS?

**Comment by mrstaggs** [comment]
It’s not a public website so I can’t elaborate on that much, but it has to load specific elements from an external JS script after the DOM loads. I’m trying to get the extension script to wait for all of the elements and other scripts to complete prior to execution of my script, but it never fires on initial page load. If I’m on the page, and I refresh it, it will attempt to load, but it ends up blocking the external scripts.

**Comment by quoid** [comment]
> and other scripts to complete

What do you mean by complete here?

You can use [`window.onload = function(){ //code };`](https://javascript.info/onload-ondomcontentloaded) to wait until all external resources are *loaded*, but if you want to wait until code is *executed*, depending on the code that is being executed, a load event might not suffice. Sometimes load events aren't the best approach, things like [mutation observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) might be better suited, but without seeing the source, I can only guess.

In my experience, I have not had issues accomplishing what you are attempting here with the extension, that's why I am interested in the source material. If you are more comfortable sending me that through email, you can find my [email here](https://github.com/quoid/userscripts/issues/37#issuecomment-615002458).

**Comment by mrstaggs** [comment]
That’s a fantastic point. I’ll poke at it some more and send you an email if I need to get into specifics. Thanks so much!

**Comment by quoid** [comment]
@mrstaggs sounds good, don't hesitate to email me if encountering issues

**Comment by NathanielRN** [comment]
> Sometimes load events aren't the best approach, things like [mutation observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) might be better suited, but without seeing the source

Just want to say this comment was extremely helpful to me as a first time web-developer. Thank you!
