### ISSUE TITLE
Global variable inaccessible

### ISSUE THREAD

**Issue by gaetgu** [quoid/userscripts#39]
I love this extension, because I primarily use safari as my browser. I had been using Tampermonkey on brave for a while just because I had to cough up two dollars if I wanted to get it on safari, so I found this and I love it! It has a great GUI and mostly works great. I have never run into an issue with it before this. I have a script that I run every once in a while on a game that I play.
```js
let t = 3;
let b = 0;
GameManager.game.currentScene.__proto__.allowUpdate=!0,GameManager.game.currentScene.__proto__.update=function(){this.allowUpdate&&(!this.state.paused&&this.state.playing&&(this.message.update(),this.updatePlayers(),this.score.update(),this.playerManager.firstPlayer.complete?this.trackComplete():this.ticks++),this.sound.update(),this.restartTrack&&this.restart(),this.vehicleTimer.update(),this.camera.update(),this.camera.updateZoom(),this.state.showDialog||(this.updateGamepads(),this.checkGamepads())),this.updateToolHandler(),this.mouse.update(),this.screen.update(),this.updateControls(),(this.importCode||this.clear)&&this.createTrack(),this.isStateDirty()&&this.updateState(),this.stage.clear(),this.draw(),this.stage.update(),this.allowUpdate=b%t==0,b++,b%=t}
```
This works perfectly fine if I just paste it into the safari console, but if I try to use it as pasted there in the extension, it doesn't run. Like I said, this is the first issue I have run into with this extension. I have tried commenting out and even removing the rest of the functions I have in it, but it still doesn't work. The site that this is supposed to run on is https://freeriderhd.com/random/track . Thanks for any help!

**Comment by quoid** [comment]
Can you provide the webpage to where you are using the script?

**Comment by gaetgu** [comment]
I edited my issue to include the webpage.

**Comment by quoid** [comment]
@gaetgu 

What is this script supposed to do?

**Comment by gaetgu** [comment]
It is supposed to slow down the framerate.

**Comment by quoid** [comment]
@gaetgu 

give me some time to investigate this further, could be a bug

**Comment by gaetgu** [comment]
@quid 
Sure! Thanks! I actually ran into another problem but it is basically the same thing :)

**Comment by quoid** [comment]
@gaetgu 

I've dug a bit into your issue. Here's what I found:

**Problem 1**
Looking at the script you linked, it seems like it is attempting to access the `GameManager` object and it's associated properties (or nested objects) to alter some values. However, the userscript is injected and executed *as soon as possible* by default. This means that the `GameManager` object might not be "ready" or even exist at the time you are trying to manipulate it; that's why you will see a `null` or `undefined` error.

In the current version of the extension, *it is the responsibility of the user to determine when the script should execute and how that should occur* - if not it will execute as soon as possible.

By pasting the above code, verbatim, into the editor you are attempting to execute that code **too soon**.

**Problem 2**
There is no "standard" for userscripts in Safari. At best, userscript managers (for Safari) are hacks, this extension included. That being said, userscripts are treated like *any other* script running on a webpage, they are **not immune** to [CSPs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). Websites with strict CSPs [*will not allow*](https://github.com/quoid/userscripts/issues/17) scripts to run from this (or any) extension through [traditional injection methods](https://github.com/quoid/userscripts/blob/0badb822f9e8a642396c7c770aa7a27193a79f40/Userscripts%20Extension/script.js#L1), so other [methods](https://github.com/quoid/userscripts/blob/c2d24f402b0571f8845bb350c6a68d39fad8b972/Userscripts%20Extension/script.js#L1) are used to circumvent strict CSPs.

This creates an interesting dilemma. By circumventing strict CSPs, you are allow userscripts to run on those websites, however you then lose some `window` context and make certain "global variables" out of reach. If this extension was to employ the "traditional" injection method, mentioned above, it would regain access to global variables, but then *would not inject on websites with strict CSPs* - so there's a tradeoff.

In your situation, you are trying to access the `GameManager` object, but that won't be accessible (in the way the userscript is coded) because it's outside the scope of the injected script. Although, you can access `GameManager` and any other global variable on websites *without strict CSPs* if you edit the code a bit (see below).

**Conclusion**
There are 2 distinct problems preventing you from executing that script. I think the first is a user problem. I think the second is either a documentation problem with the extension or a multi-faceted issue that needs a clever solution. I am currently thinking of ways to address the second issue. This also could be related to what @mrstaggs was dealing with in issue #38 - however I can't be certain.

**Solution**
That all being said, the below code works for me. Take note of the use of `window.location.host` - that determines when the script should run, edit accordingly.

```
let gameCode = `
let t = 3;
let b = 0;
GameManager.game.currentScene.__proto__.allowUpdate=!0,GameManager.game.currentScene.__proto__.update=function(){this.allowUpdate&&(!this.state.paused&&this.state.playing&&(this.message.update(),this.updatePlayers(),this.score.update(),this.playerManager.firstPlayer.complete?this.trackComplete():this.ticks++),this.sound.update(),this.restartTrack&&this.restart(),this.vehicleTimer.update(),this.camera.update(),this.camera.updateZoom(),this.state.showDialog||(this.updateGamepads(),this.checkGamepads())),this.updateToolHandler(),this.mouse.update(),this.screen.update(),this.updateControls(),(this.importCode||this.clear)&&this.createTrack(),this.isStateDirty()&&this.updateState(),this.stage.clear(),this.draw(),this.stage.update(),this.allowUpdate=b%t==0,b++,b%=t}
`;

function createGameScript() {
    let s = document.createElement("script");
    s.appendChild(document.createTextNode(gameCode));
    document.body.appendChild(s);
}

var mutationObserver = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
        var mt = mutation.target;
        let gui = document.querySelector(".gameGui");
        if (mt.id === "game-container" && gui) {
            createGameScript();
        }
    });
});

if (window.location.host === "www.freeriderhd.com") {
    mutationObserver.observe(document.documentElement, {
        attributes: true,
        characterData: false,
        childList: true,
        subtree: true,
        attributeOldValue: true,
        characterDataOldValue: false,
        attributeFilter: ["class"]
    });
}
```

**Comment by gaetgu** [comment]
Yes, that works fine, thanks! I will take some time to see how the code works in a bit, but until then it works fine! I think there should be a settings area with maybe a delay function so that you don't have to write extra code in a case like this. I will let you close this issue in case you want to keep it open for some reason. Thanks alot!

**Comment by quoid** [comment]
> I think there should be a settings area with maybe a delay function so that you don't have to write extra code in a case like this.

Javascript already has a fairly simply built in delay function, [setTimeout](https://www.w3schools.com/jsref/met_win_settimeout.asp), I am not sure how I would feel about adding that kind of setting to the extension. Also, I am not sure that is a reliable way of ensuring your code gets executed when you need it to.

Addressing problem 2 is much more complex issue, as mentioned in the above comment - it involves trade offs at the moment.

I am going to keep this issue open for visibility, but I will be editing the title to reflect the true issue.

**Comment by gaetgu** [comment]
Thanks! The only issue I can see with `setTimeout` is that it runs a script over and over, which could be problematic. There could be a way to only run the script once using `setTimeout`, so I'll have to look into that.

**Comment by kfatehi** [comment]
@gaetgu setTimeout runs once. setInterval runs repeatedly. They also return an identifier you can always pass to clearTimeout or clearInterval respectively you cancel.

**Comment by gaetgu** [comment]
@kfatehi Thanks :) I guess I mixed the two up :)

**Comment by quoid** [comment]
I am closing this issue.

Version 2.0 is imminent and I think I have a good solution with that update which I will continue to improve on.

By default the extension attempts to inject `<script>` tags into the DOM after `DOMContentLoaded`. It listens for `securitypolicyviolation` and if that it occurs it will `eval` the code.

With websites that have strict CSPs (prevent script tag injection and require eval) the window context will still be "lost", but this is the best option currently.... unless content scripts get some sort of special policy with CSPs or the extension API allows for header rewriting. Both of the options are not possible right now.

We will see what happens.
