### ISSUE TITLE
No injection with Javascripts from OpenUserJS

### ISSUE THREAD

**Issue by entisocial** [quoid/userscripts#45]
Hello, first congrats on the update, the intention behind it is good and will make it more powerful than the previous one. However for now, it isn't working for me as it doesn't inject anything. I've tried with several scripts and none work (while they work without issues on other browsers and extensions including the old version of yours).
I added the scripts by using the toolbar button, then +, then pasted my script, then saved > nothing. I disabled and enabled > nothing. I closed Safari and reopened it > nothing. I tried to change the metadata > nothing. I tried to open the app outside of Safari (it was no use)
I'm using Safari version 13.1.1 (15609.2.9.1.2) on 10.15.5 if that helps.

**Comment by quoid** [comment]
@entisocial 

I'd like to confirm whether this is an issue with the extension or the userscript(s) you are attempting to use.

Can you please try the following:

1 - create a new javascript userscript
2 - paste the below code into the editor:
```js
// ==UserScript==
// @name        Injecion Test
// @description Testing the extension
// @match       *://*.*
// ==/UserScript==

alert("test");
```
3 - save
4 - visit any website

After saving that userscript, when you visit websites you should see an alert that says "test". Note, you can disable the script by either deleting it or clicking on the toggle button once you confirm functionality is working or not.

Please let me know if that works or not. If it does work, please provide me with an example userscript that was not previously working (preferably a simple one).

---
Here are some extra notes:

- there is a [limited number of valid metadata fields](https://github.com/quoid/userscripts#userscript-metadata) for this version - pasting a userscript from a database might not work without editing on your side
- i created a new extension that [kept the 1.5.0 functionality](https://github.com/quoid/InjectJS) in case some users prefer the more "lightweight" version

**Comment by entisocial** [comment]
Ok, the test does work properly. For instance this script https://openuserjs.org/scripts/tumpio/Endless_Google/source works with InjectJS, but doesn't with Userscripts.

**Comment by quoid** [comment]
OK, then this is technically a userscript (source file) issue, not an extension issue.

Taking a look at the script you've linked, it does not have the required metadata fields in order to run - [see docs](https://github.com/quoid/userscripts#userscript-metadata)

> @match (optional) - Domain match patterns; you can use several instances of this metafield if you'd like multiple domain matches. ***If you omit this metafield, the userscript will never run***. View [this article for more information on constructing patterns](https://developer.chrome.com/extensions/match_patterns)

I can see that the script you linked uses the old way of matching domains, with `// @include `. Userscript Safari does not support that metadata field. Theoretically if the `// @include` value is a string or conforms to a match pattern, you could change `@include` to `@match` and it could/should work. 

I tried that with the script you linked and injection *did* happen when switching from `@include` to `@match`, however it looks like the script is severely outdated and did not function.

Some userscripts will contain metadata fields that are not supported by this extension. There are plans to implement support for more fields, specifically focusing on fields that augment functionality (such as `@run-at`, `@downloadURL`, etc...). I am unsure if `@inject` will be priority, but I think making it an alias for `@match` could be a good idea.

**Comment by entisocial** [comment]
Oh nice, indeed replacing `@include` by `@match` fixes my unworking scripts, thanks for the tip!
I did read the doc about `@match` but I got confused with it being "optional" and at the same time mandatory for the script to run plus I overlooked the fact that my scripts were using `@include` instead. But it's all working now thanks again for your good work 👍🏻

**Comment by quoid** [comment]
Now that you point that out, the wording is awkward. The field is bot needed to save but required to run the script. 

I'll try to make that more clear.
