### ISSUE TITLE
@require: supports Pastebin url

### ISSUE THREAD

**Issue by lgxz** [quoid/userscripts#485]
Because we can't add .cs or .js extension to a Pastebin url, so it's not possible to @require from Pastebin.

Is it possible to validate file type by other methods instead of file path? 

For example:
1. Add require_css and record_js commands.
2. Support https://pastebin.com/raw/SW9RLDct?file=x.js. That is, determine file type by the end of URL.

**Comment by quoid** [comment]
> Yes. But every script will download and save the same @require item to its own storage directory.
There are multiple copies of the same required items.

It is the onus of the user script developer to use the `@require` fields in a way that does not duplicate resources.

Sharing resources between user scripts is tricky because it would require user scripts to be able to read data from other user scripts and not have them isolated from each other. Obviously this is not supported and plans for this do not currently exist.

> It's much better if we have a "Project" concept.

As mentioned this is currently outside of the scope of this project, but if you have ideas for this, I would suggest making a pull request with the concept. I'm happy to review improvement PRs, but bear in mind, making a pull request with conceptual changes doesn't guarantee they will be accepted into the project.
