### ISSUE TITLE
how to install scripts on iOS

### ISSUE THREAD

**Issue by Y0usefmahdi** [quoid/userscripts#499]
Is there a way to install scripts on iOS without the need for MacOS? I've read the documents, but I couldn't find any information on how to do this.

**Comment by zaptrem** [comment]
> Of course you can. It's actually similar to how the macOS version is used. You can:
> 
> * manually put the script file in the `save location` folder you set
> * open the online `.user.js` url in your Safari and click on popup, you will see the [Install Prompt](https://github.com/quoid/userscripts#popup)
> 
> We understand that the current OOBE is not clear enough and users sometimes can't find their way around if they don't have relevant experience using it. We plan to improve this in the next major release. #500

Doesn’t work with this script url: https://bin.socialspill.com/raw/oxozu

**Comment by quoid** [comment]
> Doesn’t work with this script url: https://bin.socialspill.com/raw/oxozu

The [check](https://github.com/quoid/userscripts/blob/4a4c257f14c98cf55115f6cb9c258946efd6d21c/src/popup/App.svelte#L342) is fairly rudimentary and without the `user.js` suffix it won't pick up on the fact the user is viewing a user script.

> Why isn’t there a way to manually trigger the script addition or a plus button like on MacOS?

Time, lack of contributors, other priorities? Simply put, because it hasn't been planned nor implemented in the iOS version. Pull requests are always welcome if you feel up to it, but I am unsure where and how in the current iOS UI  a plus button would fit.
