### ISSUE TITLE
URL matching did not work in presence of redirection

### ISSUE THREAD

**Issue by ed9w2in6** [quoid/userscripts#55]
_System Information:_
> macOS version 10.15.6（19G73）
> userscripts version 2.0.0
> Safari version 13.1.2（15609.3.5.1.3）

# Question regarding the URL matching mechanism

Here is a _**popup AD website**_ that redirects you to another AD that buy AD service from them.
( WARNING: _Usually a World of Warships AD, but sometimes NSFW ones._ )

https://wadiryphi.pro/bb3cV.0dP-2fhg0hYiX_RkilPmTnE-mpcqnrJsp_ZuDv1wlxY-jzgA2BYCz_gE0FNGDHJ-kJMKWLJMi_NODPIQ4RZ-TTkU1VNWz_cY3ZYaTbU-4dOeTfdgm_OiDjMk1lM-inZoypcq3_JsjtPuWvh-pxcy3zRAv_cCnDlEiFY-WHNIrJJKn_NMJNZODP0-yRNSTTEU1_MWTXgY3ZJ-nbpcvdbem_VgJhZiDj0-ylNmTnEo1_MqTrgs3t

I wrote a simple script that
I try to match the above url with `@match *://wadiryphi.*/*` as well as `@match *://*.wadiryphi.*/*`.
But for some reason it did not work.

It worked properly if I use the JS console and run 
```javascript
window.location.assign('<the_url>')
```

But it did not work when it is _**opened as a link**_ or _**typed into the URL text-box**_ in Safari.

- I suspect that this is due to the timing when the extension code is fired, but I am not sure how to debug this.

---------------------------

Or is this falling out of the use case of this application?
I know there are better way in doing this such as filtering at router,
or filtering by editing `/etc/hosts`, but I do not want to do these.

**Comment by quoid** [comment]
@ed9w2in6 

can you add this match pattern and try?

`*://wadiryphi.*`

**Comment by ed9w2in6** [comment]
I tried matching `*://wadiryphi.*` as well and it did not work.

------------------------

What I am trying to do is to block popup ADs / unwanted sites such as iclickcdn, popcash, wadiryphi.
Basically I stop them from loading and redirect it to Google.  
It is a very simple script:

```javascript
console.log('userscript: matched unwanted sites, stopping, will redirect to' +
            ' google.com');
window.stop();
window.location.assign('https://www.google.com/search?q=Filtered+by+userscipt')
```

Because sometimes these sites spawns multiple windows ( bypassing the Adblocker ), and they got annoying Javascripts thats prompts you before closing each window.

I want to implement this function using this extension so it can be at application level and does not do any system wide changes, such as editing `/etc/hosts`.

**Comment by quoid** [comment]
@ed9w2in6 

From my testing, it *is* matching properly and most of the time executes the script. I say most of the time because no matter how script injection works (`DOMContentLoaded` or immediately), it does sometimes fail to inject for unknown reasons.

But I don't think the issue lies with the extension or the injection method. You can test my other extension, [InjectJS](https://github.com/quoid/InjectJS) if you want to see how it would behave with scripts that are injected *immediately*. However, I've already tested that and there's no measurable difference.

I figured you were trying to stop the redirects so did a little testing. I believe the actual issue is the methods that that website is using to create the redirects. They are using a number of techniques, but the main one is utilizing `<meta http-equiv=refresh content=...>`. I am currently unaware of any option in Safari to prevent "refreshes" with meta tags, however mostly all other browser have an option to prevent this.

I also can't seem to find a reliable way to prevent the meta tag from executing, I imagine it is because the time to refresh is set to `0`. I tried `window.stop();` as you did and a bunch of other techniques (removing some/all DOM content). 

Like I mention above, it doesn't matter if the script is inject at `DOMContentLoaded` or immediately, the result seems to be the same.

I think Safari needs an option to disable `meta` tag refreshes like other modern browsers. If you know of this setting please let us know how to enable it.

**Comment by ed9w2in6** [comment]
One unrelated question:  Is it true that user scripts cannot execute on file urls `file://*` at the moment?  I know it is possible on Chrome but does it break any security constrains on Safari?

**Comment by ed9w2in6** [comment]
@quoid 

Yea I curled the html and notice the same problem.
I agree with your comment on Safari's lack of disabling `meta` tag refreshes.

But I think the problem is really with the embedded `form` tag.
Because the `meta` tag with refresh set to `0` is wrapped within a `noscript` tag.  The remaining `meta` tag has its refresh set to `10`.

I tried and it only works when the `form` is removed.

**Comment by quoid** [comment]
@ed9w2in6 

> I will open another issue, do not need to answer this.

I appreciate that, but it's ok since it's somewhat related.

Unfortunately content scripts need [`http` or `https`](https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_info_property_list_keys/about_permissions_for_scripts_and_style_sheets) scheme to be injected. Right now, `file` wont work.

> But I think the problem is really with the embedded form tag.

I think you are right.

Here's the source I got below:

```
<!doctype html>
<html lang=en>
<meta charset=utf-8>
<meta name=robots content="noindex, nofollow">
<meta http-equiv=refresh content="10; URL=https://wadiryphi.pro/cnG-Fpzqc.2rIs/_cunvJwpxZ-Dz1AlBYCj_gE2FYGzHg-0JNKDLJMk_MOWPJQiRN-DTIU4VZWT_kY1ZNazbc-3dYeTfUg4_OiTjdkmlO-DnMo1pMqi_Zsytcu3vJ-jxPyWzhAp_cC3DREvFc-nHlIiJYKW_NMrNJOnPR-2RcSjT0Uw_JWnXpYvZb-mbVcJdZeD_0gyhNijjk-2lMmDnQoz_">
<noscript><meta http-equiv=refresh content="0; URL=https://wadiryphi.pro/cnG-Fpzqc.2rIs/_cunvJwpxZ-Dz1AlBYCj_gE2FYGzHg-0JNKDLJMk_MOWPJQiRN-DTIU4VZWT_kY1ZNazbc-3dYeTfUg4_OiTjdkmlO-DnMo1pMqi_Zsytcu3vJ-jxPyWzhAp_cC3DREvFc-nHlIiJYKW_NMrNJOnPR-2RcSjT0Uw_JWnXpYvZb-mbVcJdZeD_0gyhNijjk-2lMmDnQoz_">
</noscript>
<title>Redirecting...</title>
<form method=post action=https://wadiryphi.pro/coGpF.zqc_zs9tfucvm-VxxyVzGAl_tCZDTE0Fx-NHTIkJ1KN_jMgNzONPT-UR5SMTjUI_1WNXjYgZy-ObTcUdzeJ_mghh0iYjX-RlimPnToE_mqcrHsQt9-TvWwpxZyN_UA5BqCQDT-BFNGeHVIF_4KTLlMRNr-MPUQ5RqSZ_3UpVOWVXF-UZ1aSbkcZ_WeVfEgphH-SjnkllimM_koZprqWrW-1tGudvVwp_DyUzmAhBi-bDTElF1GZ_VIcJxKdLm-RNYOTPWQt_KSRT1UEVw-TXVYdZRaN_FckdyeUfT-VhPiRj1kl_3mTnUodpJ-erUs1tEuU_mwxxPyVzG-dB3CTDUER_rGNHUI9JH-VLmMpNaOa_mQcRwSTTW-pVkWbXEYp_EaYbzcRdN-VfGgch0iT_lkRlNmNnE-1p3qLrSs0_mucvnwJxp-ZzDA1BlCY_jEgF2GYHz-gJ0KNLDMJ_kOMPWQJRi-NTDUIV4WZ_TYkZ1aNbz-cd3eYfTgU_4iOjTkdlm-OnDoMp1qM_isZtyucv3-JxjyPzWAh_pCcD3ERFv-cHnIlJiKY_WMNNrOJPn-NRJSZTDU0_yWNXTYEZ1-MbTcgd3eJ_ngphvibjm-VlJmZnDo0_yqNrjskt2-MvDwQxzy id=goform>
<input type=hidden name=jswgr id=jswgr>
<input type=hidden name=jswgvr id=jswgvr>
<input type=hidden name=jssh id=jssh>
<input type=hidden name=jsih id=jsih>
<input type=hidden name=jsah id=jsah>
</form>
<script>
    try{
        document.getElementById("jssh").value=screen.height;
        document.getElementById("jsih").value=innerHeight;
        document.getElementById("jsah").value=screen.availHeight;
        var canvas=document.createElement("canvas");
        var gl=canvas.getContext("webgl")||canvas.getContext("experimental-webgl");
        if(gl){
            document.getElementById("jswgr").value=gl.getParameter(gl.RENDERER);document.getElementById("jswgvr").value=gl.getParameter(gl.VENDOR);
        }
    }catch(e){

    }
    window.opener=null;
    document.getElementById("goform").submit();
</script>
```

**Comment by quoid** [comment]
Could you post the source you got? 

I am wondering if the form is dynamically generated. I cant seem to be able to remove it, that's why I was thinking it was more to do with the meta tags.

**Comment by ed9w2in6** [comment]
@quoid 

Yes I think the form are dynamically generated.  The URL are different everytime I curled it.
The URL are the same for the `meta` tags and different with the `form` tag

```html
<!doctype html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=robots content="noindex, nofollow">
  <meta http-equiv=refresh content="10; URL=https://wadiryphi.pro/cwGxF-z.cz2AIB/Cc_nEJFpGZHD-1JlKYLjMg_2OYPzQgR0-NTDUJVkWM_WYJZiaNbD-Id4eZfTgk_1iNjzkcl3-YnToUp4qO_TsdtmuOvD-Mx1yMziAZ_yCcD3EJFj-PHWIhJpKc_3MRNvOcPn-lRiSYTWUN_rWJXnYRZ2-cbjc0dweJ_ngphvibjm-VlJmZnDo0_yqNrjskt2-MvDwQxzy">
  <noscript>
    <meta http-equiv=refresh content="0; URL=https://wadiryphi.pro/cwGxF-z.cz2AIB/Cc_nEJFpGZHD-1JlKYLjMg_2OYPzQgR0-NTDUJVkWM_WYJZiaNbD-Id4eZfTgk_1iNjzkcl3-YnToUp4qO_TsdtmuOvD-Mx1yMziAZ_yCcD3EJFj-PHWIhJpKc_3MRNvOcPn-lRiSYTWUN_rWJXnYRZ2-cbjc0dweJ_ngphvibjm-VlJmZnDo0_yqNrjskt2-MvDwQxzy">
  </noscript>
  <title>Redirecting...</title>
  <form method=post action=https://wadiryphi.pro/c.G_Fuzvcwzx9-fzcAmBVCx_VEGFlGtHZ-TJ0KxLNMT_kO1PNQjRg-1TOUDVEW3_NYjZUa3bN-TdIeyfNgz_AiyjJkmlh-0nYoXpRqi_PsTtEumvc-HxQy9zTAW_pCZDNEUF5-qHQITJBKN_eMVNFO4PT-lRRSrTMUU_5WqXZYzZF-PbRcEdUez_SgkhViojT-ElpmHnSon_lqirMsktZ-rvWwWx1yG_dAVBpCDDU-WFtGKHRI0_kKyLTMkNd-RPeQkR9SE_VUmVpWOXb-VZUa1bWcX_peNfNgEh1-tjVkmltmZ_aokplq3rT-mtpuSvawF_pyUzRAXBp-NDaEkFlG5_WIkJRKJLM-kNpOEPWQT_NSOTRUFVU-xXTYkZRaJ_Mckd1enfL-Sh0imjckn_JmpnZoDp1-lrYsjtgu2_Ywzxgy0zN-DBJCkDMEW_JGiHNIDJI-4LZMTNkO1_NQzRcS3TY-TVUW4XOYT_dambOcDdM-1fMgihZiy_ck3lJmjnP-Wphqprcs3_Ruvvcwnxl-izYAWBNCr_JEnFNGJHZ-DJ0KyLNMT_EO1PMQTRg-3TJUnVpWv_bYmZVaJbZ-Dd0eyfNgj_ki2jMkDlQ-zn id=goform>
    <input type=hidden name=jswgr id=jswgr>
    <input type=hidden name=jswgvr id=jswgvr>
    <input type=hidden name=jssh id=jssh>
    <input type=hidden name=jsih id=jsih>
    <input type=hidden name=jsah id=jsah>
  </form>
  <script>
    try {
        
        document.getElementById("jssh").value = screen.height;
        document.getElementById("jsih").value = innerHeight;
        document.getElementById("jsah").value = screen.availHeight;
        var canvas = document.createElement("canvas");
        var gl     = canvas.getContext("webgl")||canvas.getContext("experimental-webgl");
        if ( gl ) {
            
            document.getElementById("jswgr").value  = gl.getParameter(gl.RENDERER);
            document.getElementById("jswgvr").value = gl.getParameter(gl.VENDOR);
        }
    } catch ( e ) {}
    
    window.opener = null;
    document.getElementById("goform").submit();
  </script>
</html>
```


------------------------

And by removing the `form` tag I mean I downloaded it and hosted it locally.

That is the reason I wanted to open a new issue so if some one ask about matching `file://` URLs, one can refer to that new issue.

I have some other questions anyway, for example I cannot seems to match `*://localhost` or `*://127.0.0.1`

**Comment by quoid** [comment]
I am not exactly sure how these redirection sites work, but I'm seeing this source in the console as well, when I check int he network tab.

```html
<html>
<head>
    <meta http-equiv="x-dns-prefetch-control" content="on">
    <meta http-equiv="refresh" content="0;URL=https://www.pcgmer.com/oc/33ea5c8551?affclick=h5rzkdiinptk21jkpii4&amp;pubid=M9650G5FN">

    

    <script>window.opener = null</script>
    <script>document.location.href = "https:\/\/www.pcgmer.com\/oc\/33ea5c8551?affclick=h5rzkdiinptk21jkpii4\x26pubid=M9650G5FN";</script>
</head>
<body></body>
</html>
```

**Comment by quoid** [comment]
feel free to test methods to prevent this on my website:

- https://www.k21p.com/meta.html - redirects to duckduckgo.com by a meta refresh
- https://www.k21p.com/form.html - redirects to hacker news by a form submission
- https://www.k21p.com/location.html - redirects to github.com by a window.location.href change

**Comment by ed9w2in6** [comment]
This one did not work for me: https://www.k21p.com/location.html.

I was redirected to Github instead.

**Comment by quoid** [comment]
> This one did not work for me: https://www.k21p.com/location.html.

I was checking in private tabs and every private tab sent me to duckduckgo. Checking in non-private tabs it *does* send me to github.

However, with my other extension, it seems to reliably send me to duckduckgo every time. I believe this is because the script is executing immediately rather than after DOMContentLoaded.

Im planning a future update to implement `@run-at` metafield which will allow users to choose when to inject. That will improve situations like this.

---

I think the issue has more to do with methods that were being used for redirection rather than URL matching or script execution timing. It has certainly reinforced the idea that `@run-at` will be beneficial.

Unless you have anything more to add to this, I will close the issue int he coming days.

**Comment by ed9w2in6** [comment]
haha i was testing on the same thing as well.

The `@run-at` metafield sounds great.

I do not have anything to add at the moment.

I will look forward for the future update.

Many thanks for your help!

Feel free to close the issue.
