### ISSUE TITLE
Uploading a file requested by a userscript seems to fail

### ISSUE THREAD

**Issue by slingshotocelot** [quoid/userscripts#77]
The script I'm using is FrankerFaceZ ([userscript](https://cdn.frankerfacez.com/static/ffz_injector.user.js) and [full codebase](https://github.com/FrankerFaceZ/FrankerFaceZ)). FFZ allows you to save configurations by exporting or importing a JSON file, but importing a JSON file seems to fail. I'm given the usual dialog to pick a file, but after choosing it nothing happens. Unfortunately this fails silently, with no messages from FFZ logged on the console. FFZ's backup/restore still works in other browsers (tested in Chrome), and also worked in Safari 13 and Safari Technology Preview before the Safari 14 release, although I can't say for sure which Userscripts version I had then.

_System Information:_
> macOS version: 10.15.6
> Userscripts version: 2.1.3
> Safari version: 14.0 (15610.1.28.1.9, 15610)

**Comment by quoid** [comment]
@slingshotocelot 

from what I can tell, the extension is properly loading the userscript on twitch

as far as the specific functionality *within* the userscript, I am not sure that is an issue with this extension but rather an issue with the userscript itself - wouldn't it be better place in that repo? https://github.com/FrankerFaceZ/FrankerFaceZ

It could be possible that Safari 14 changed in someone that is breaking that specific userscripts functionality

**Is there a reason you think this issue might be specific to *this* extension?**

**Comment by quoid** [comment]
is this what you're expecting to happen when restoring from backup?

<img width="668" alt="Screen Shot 2020-09-20 at 09 27 56" src="https://user-images.githubusercontent.com/7660254/93714091-60d72000-fb2e-11ea-8d11-85241bea7626.png">

**Comment by slingshotocelot** [comment]
Yes, that's what I'm expecting, and it's working for me as well now. No idea what changed, since it doesn't look like there were any new relevant commits on the extension's end. (Sorry for raising an issue about something that might have been extension-specific, I only really use Userscripts for this script so I wasn't sure.)

**Comment by quoid** [comment]
@slingshotocelot 

> Sorry for raising an issue about something that might have been extension-specific, I only really use Userscripts for this script so I wasn't sure.


No need to apologize, I just wanted to make sure there wasn't something I was missing and I am glad to help when I can.

> No idea what changed, since it doesn't look like there were any new relevant commits on the extension's end.

Yeah, I am unsure as well. When I posted the above screenshot, I had to do some weird things to get the file to upload properly, but currently it just seems to work. I was thinking that the author might have pushed a hotfix (since the actual script is just a request made by the main userscript), but as you said, there are no new commits. ¯\_(ツ)_/¯

I am glad it's working now, I am going to close this issue. Don't hesitate to open a new issue in the future if you encounter issues.
