### ISSUE TITLE
Ability to control order of injection

### ISSUE THREAD

**Issue by CalmBit** [quoid/userscripts#78]
Hi there,

I've got a couple of Userscripts that require executation/injection ordering in order to properly function. 

Specifically, scripts that are dependent on [this](https://greasyfork.org/en/scripts/38582-wanikani-open-framework) framework are usually required to have this script run first (the installation forum post [here](https://community.wanikani.com/t/installing-wanikani-open-framework/28549) details how this is accomplished with Tampermonkey.)

Is there any plan for a feature like this, or something that allows for variable priority of scripts?

**Comment by quoid** [comment]
@CalmBit 

The next planned update is supposed to address #64 (and others enhancements) which will allows users to set when a script executes (document-start, end or idle). This would *sort of* allow you to control execution times by setting one script to execute at start, the others at end, etc... This isn't as clean as a solution like you linked from Tampermonkey, however it could work.

Alternative options:

1) introduce a new meta field, something like `@order`, the lower the order number, the sooner it executes or gets written to the dom

2) some frontend solution like Tampermonkey uses. I'd like to avoid complex script specific settings in the frontend right now, so that kind of implementation would require some thought.

---

What are your thoughts on the above?

**Comment by CalmBit** [comment]
I think the initial proposition _might_ work, and it's at the very least still a good tool for certain stuff. The alternative option no. 1 might be ideal for fine-grained control like this, but I'd imagine it'd only need implementation if the first idea doesn't work. I'll  see if the first idea works and report back, and in the meantime patiently await the next update. Thank you!

**Comment by quoid** [comment]
@CalmBit 

I might have a beta build ready soon which will have this feature, if you want you can [sign up](https://forms.gle/QB46uYQHVyCxULue9) for beat builds or you can email me directly if you don't want to use google forms for privacy reasons.

**Comment by CalmBit** [comment]
Testing the beta build, I'm not having any luck with it. WOF (the aforementioned timing-sensitive user script) by default _apparently_ uses the `@run-at document-start` metadata, but despite this (plus testing it with with `@weight`, which is a super cool extra level of granularity, thank you 😄 ) I'm not able to get it working. For troubleshooting purposes, I'm running Safari 13.0.5 on Catalina 10.15.3, on a Late 2013 MacBook Pro. I set WOF to weight 999, and the dependent script to weight 1, and gave the dependent script `@run-at document-end` just to be sure I wasn't missing anything, but the dependent script still asks for the framework to be run first.

**Comment by quoid** [comment]
@CalmBit can you paste the metablock of your script?

I am going to open a new issue in a second, can you post it there?
