### ISSUE TITLE
How can I get it to play nicely with the Social Fixer userscript?

### ISSUE THREAD

**Issue by mystrd** [quoid/userscripts#82]
_System Information:_
> macOS version: 10.15.7
> Userscripts version: 2.2.0
> Safari version: 14.0 (15610.1.28.1.9, 15610)

Am trying to get the very popular Social Fixer user script to work? Thought it would be as simple as copying and pasting the script from [https://socialfixer.com/socialfixer.user.js](https://socialfixer.com/socialfixer.user.js) but it's not working on Facebook.

**Comment by quoid** [comment]
@mystrd that userscript uses many keys that are not yet supported by this extension, such as `@connect`, `@grant` and `@include ` with `regex` expressions. Looking through the code it seems like it *could* work with this extension if it was refactored a bit.

I don't use Facebook so I can't comment on how to go about fixing it and I doubt the author of the userscript would want to refactor it.

It will be a while before `@grant` is supported, if ever and I don't have immediate plans to support `@include` with `regex` since the `@match` key is safer.

Sorry I couldn't be of more help.

**Comment by mystrd** [comment]
No worries, greatly appreciated!

Sent from my iPhone

On 16 Oct 2020, at 21:02, Justin Wasack <notifications@github.com> wrote:

﻿

@mystrd<https://github.com/mystrd> that userscript uses many keys that are not yet supported by this extension, such as @connect, @grant and @include with regex expressions. Looking through the code it seems like it could work with this extension if it was refactored a bit.

I don't use Facebook so I can't comment on how to go about fixing it and I doubt the author of the userscript would want to refactor it.

It will be a while before @grant is supported, if ever and I don't have immediate plans to support @include with regex since the @match key is safer.

Sorry I couldn't be of more help.
