### ISSUE TITLE
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

### ISSUE THREAD

**Issue by MarcYin** [quoid/userscripts#84]
Updated to the newest version of Userscripts, but the previously worked script is not working anymore and the error:
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

_System Information:_
> macOS version:10.15.7
> Userscripts version:2.2.0
> Safari version:14.0

**Comment by quoid** [comment]
@MarcYin Please include the script metadata and the website you are trying to execute it on. 

From the error you listed this seems to be a Content Security Policy issue. The probable reason it just now stopped working is likely due to the new metadata fields that were implemented in a recent update. It gives the user more control but not longer automatically defaults to strict CSP fallbacks unless explicitly set by the user.

**Comment by quoid** [comment]
If you add `// @inject-into     auto` does it resolve your issue?

**Comment by MarcYin** [comment]
Hi, it has resolved the issue and work as normal again. Thanks a lot!
